---
title: "p8105_hw2_ao2965"
author: "Alissa Shams Orchi"
date: "2025-09-30"
output: github_document
---

Importing Trashwheel and modifying Mr.Trash Wheel sheet

```{r}
library(tidyverse)
library(readxl)
trash_df <- read_excel(
 "202509 Trash Wheel Collection Data.xlsx",
 sheet = "Mr. Trash Wheel",
 range = "A2:N709",
 na = c("NA", ".", "")
) |>
 janitor::clean_names() |>
 mutate(
 table = "mr.trash wheel", 
 sports_balls = as.integer(round(sports_balls)),
 year = as.numeric(year)
) |>
 select (dumpster, month, year, date, table, everything())
```

Importing Trashwheel and modifying Professor Trash Wheel sheet

```{r}
library(tidyverse)
library(readxl)
proff_df <- read_excel(
 "202509 Trash Wheel Collection Data.xlsx",
 sheet = "Professor Trash Wheel",
 range = "A2:M134",
 na = c("NA", ".", "")
) |>
 janitor::clean_names() |>
 mutate(
 table = "professor trash wheel"
 ) |>
select (dumpster, month, year, date, table, everything())
```
Importing Trashwheel and modifying Gwynns Falls Trash Wheel sheet
```{r}
library(tidyverse)
library(readxl)
gwynns_df <- read_excel(
 "202509 Trash Wheel Collection Data.xlsx",
 sheet = "Gwynns Falls Trash Wheel",
 range = "A2:L351",
 na = c("NA", ".", "")
) |>
 janitor::clean_names() |>
 mutate(
 table = "gwynns falls trash wheel"
 ) |>
select (dumpster, month, year, date, table, everything())
```

Combining the tables
```{r}
trash_tidy=
  bind_rows(trash_df, proff_df, gwynns_df)
```

